; PM-App production PHP settings
date.timezone = Asia/Jakarta
memory_limit = 512M
upload_max_filesize = 12M
post_max_size = 64M
max_execution_time = 120
expose_php = Off

opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 192
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
